% Bernard Gonzales
% JPEG Data Compression
% EE652
% Description: 

function [DisplayBox] = TextUpdate
% Creates a textbox.
DisplayBox.fh = figure('units','pixels',...
              'position',[40 40 500 940],...
              'menubar','none',...
              'resize','off',...
              'numbertitle','off',...
              'name','Program output');
DisplayBox.tx = uicontrol('style','edit',...
                 'units','pix',...
                 'position',[10 60 480 830],...
                 'backgroundcolor','w',...
                 'HorizontalAlign','left',...
                 'min',0,'max',10,...
                 'enable','inactive',...
                 'FontSize', 17);
